[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "1.3.3" }
random-string = { version = "1.0.0" }
serde = { version = "1.0", features = ["derive"] }
sled = { version = "0.34.7" }
